In [1]:
import numpy as np

In [2]:
# A list of salaries ranging from 50,000 to 150,000
import random

salary_list = [random.randint(50000, 100000) for _ in range(10_000_000)]

In [3]:
import statistics

In [4]:
%%timeit

statistics.median(salary_list)

5.12 s ± 379 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


NumPy saves a lot of time in these type of cases...

In [5]:
%%timeit

np.median(salary_list)

882 ms ± 37.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


---

In [6]:
import numpy as np

In [7]:
my_array = np.array([1, 2, 3, 4])

In [8]:
my_array

array([1, 2, 3, 4])

In [9]:
my_array.mean()

np.float64(2.5)

In [10]:
# Job titles
job_titles = np.array(["Data ANalyst", "data Scientist", "Data Enginner", "Machine Learning Engineer"])

# Base Salaries
base_salaries = np.array([60000, 80000, 75000, 90000])

# Bonus rate
bonus_rates = np.array([.05, .1, .08, .12])

In [11]:
total_salaries = base_salaries * (1 + bonus_rates)

total_salaries

array([ 63000.,  88000.,  81000., 100800.])

In [12]:
np.mean(total_salaries)

np.float64(83200.0)

In [13]:
# Job titles
# Suppose we have a job title and we don't have any info on its base salary and bonus rate, we will use nan (not a number) in such cases

job_titles = np.array(["Data ANalyst", "data Scientist", "Data Enginner", "Machine Learning Engineer", "AI Engineer"])

# Base Salaries
base_salaries = np.array([60000, 80000, 75000, 90000, np.nan])

# Bonus rate
bonus_rates = np.array([.05, .1, .08, .12, np.nan])

In [14]:
total_salaries = base_salaries * (1 + bonus_rates)

total_salaries

array([ 63000.,  88000.,  81000., 100800.,     nan])

In [16]:
np.nanmean(total_salaries)

np.float64(83200.0)